info:
    component:
        Security Server

server:
    port: 9001
    ssl:
        key-store: classpath:keystore.jks
        key-store-password: password
        key-password: password
# contextPath表示上下文；路径
#    contextPath: /auth

# 暂时使用硬编码
security:
    user:
        nam: client
        password: password
    ignored: /css/**,/js/**,/favicon.ico,/webjars/**
#    oauth2:
#        resource:
#            filter-order: 3
logging:
    level:
        org.springframework.security: DEBUG