info:
    component:
        Security Server
spring:
    application:
        name: security-service
server:
    port: 9001
    ssl:
        key-store: classpath:keystore.jks
        key-store-password: password
        key-password: password
# contextPath表示上下文；路径
#    contextPath: /auth

# 暂时使用硬编码
security:
    user:
        nam: client
        password: password
    ignored: /css/**,/js/**,/favicon.ico,/webjars/**
#    oauth2:
#        resource:
#            filter-order: 3
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 3
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

logging:
    level:
        org.springframework.security: DEBUG